//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZesuSite.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Header2
    {
        public byte ID { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string Saat { get; set; }
        public string Baslik { get; set; }
        public string Header1 { get; set; }
        public string Adres { get; set; }
    }
}
