//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZesuSite.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZesuEntities : DbContext
    {
        public ZesuEntities()
            : base("name=ZesuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ZesuAdmin> ZesuAdmin { get; set; }
        public virtual DbSet<ZesuMesaj> ZesuMesaj { get; set; }
        public virtual DbSet<Kurumsal> Kurumsal { get; set; }
        public virtual DbSet<SirketDurum> SirketDurum { get; set; }
        public virtual DbSet<Hizmetler> Hizmetler { get; set; }
        public virtual DbSet<Footer> Footer { get; set; }
        public virtual DbSet<Header> Header { get; set; }
        public virtual DbSet<Header2> Header2 { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<AnaResim> AnaResim { get; set; }
        public virtual DbSet<AltResim> AltResim { get; set; }
        public virtual DbSet<Hakkimizda> Hakkimizda { get; set; }
        public virtual DbSet<BambuUrun> BambuUrun { get; set; }
        public virtual DbSet<BayanUrun> BayanUrun { get; set; }
        public virtual DbSet<CocukUrun> CocukUrun { get; set; }
        public virtual DbSet<ErkekUrun> ErkekUrun { get; set; }
        public virtual DbSet<SporcuUrun> SporcuUrun { get; set; }
        public virtual DbSet<AnaArkaResim> AnaArkaResim { get; set; }
    }
}
